# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - dev-parent-master

pool:
  name: Default

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
    displayName: "Install Node.js"

  - script: |
      npm install -g yarn
      yarn install
      npm run build:dev
    displayName: "npm install and build"
  - task: Docker@2
    displayName: buildAndPush
    inputs:
      containerRegistry: ken42registry
      repository: "ken42/parent-portal-nginx"
      Dockerfile: Dockerfile
  - task: CopyFiles@2
    displayName: "Copy Files to: $(build.defaultworkingdirectory)"
    inputs:
      Contents: |
        **/*.yaml
      TargetFolder: "$(Build.defaultworkingdirectory)"
  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: drop"
    inputs:
      PathtoPublish: "$(Build.defaultworkingdirectory)"
      artifactName: "drop"
      